
const _baseUrl = "https://localhost:7133/api";
export default {
    Login: `${_baseUrl}/Authentication/Login`,
    Register: `${_baseUrl}/Authentication/Register`,
    Products: `${_baseUrl}/Product/GetAll`,
    Product: `${_baseUrl}/Product/Get`,
    CreateProduct: `${_baseUrl}/Product/Create`,
    UpdateProduct: `${_baseUrl}/Product/Update`,
    DeleteProduct: `${_baseUrl}/Product/Delete`,
    Rooms: `${_baseUrl}/Room/GetAll`,
    Room: `${_baseUrl}/Room/Get`,
    CreateRoom: `${_baseUrl}/Room/Create`,
    UpdateRoom: `${_baseUrl}/Room/Update`,
    DeleteRoom: `${_baseUrl}/Room/Delete`,
    Stores: `${_baseUrl}/Store/GetAll`,
    Store: `${_baseUrl}/Store/Get`,
    CreateStore: `${_baseUrl}/Store/Create`,
    UpdateStore: `${_baseUrl}/Store/Update`,
    DeleteStore: `${_baseUrl}/Store/Delete`,
    Structures: `${_baseUrl}/Structure/GetAll`,
    Structure: `${_baseUrl}/Structure/Get`,
    CreateStructure: `${_baseUrl}/Structure/Create`,
    UpdateStructure: `${_baseUrl}/Structure/Update`,
    DeleteStructure: `${_baseUrl}/Structure/Delete`,
    WorkOrders: `${_baseUrl}/WorkOrder/GetAll`,
    WorkOrder: `${_baseUrl}/WorkOrder/Get`,
    CreateWorkOrder: `${_baseUrl}/WorkOrder/Create`,
    UpdateWorkOrder: `${_baseUrl}/WorkOrder/Update`,
    DeleteWorkOrder: `${_baseUrl}/WorkOrder/Delete`,
    Users: `${_baseUrl}/User/GetAll`,
    User: `${_baseUrl}/User/Get`,
    UpdateUser: `${_baseUrl}/User/Update`,
    DeleteUser: `${_baseUrl}/User/Delete`,
    ChangePassword: `${_baseUrl}/User/ChangePassword`
}
